

run: solution/solution.go
	cd solution && go run . 7 27

run-final: solution/solution.go
	cd solution && go run . 200000000000000 400000000000000


run2: solution2/solution2.go
	cd solution2 && go run .
