
build: solution.scala
	scalac solution.scala

Solution.class: solution.scala
	scalac solution.scala

run: Solution.class
	scala Solution



build2: solution2.scala
	scalac solution2.scala

Solution2.class: solution2.scala
	scalac solution2.scala

run2: Solution2.class
	scala Solution2
