

solution.jar: solution.kt
	kotlinc solution.kt -include-runtime -d solution.jar

run: solution.jar
	java -jar solution.jar



solution2.jar: solution2.kt
	kotlinc solution2.kt -include-runtime -d solution2.jar

run2: solution2.jar
	java -jar solution2.jar
